src/Entity/Bank.php
<?php

namespace App\Entity;

use App\Repository\BankRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BankRepository::class)
 */
class Bank
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=8)
     */
    private $short_name;

    /**
     * @ORM\Column(type="text", nullable=false)
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity=Check::class, mappedBy="bank")
     */
    private $checks;

    public function __construct()
    {
        $this->checks = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->short_name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getShortName(): ?string
    {
        return $this->short_name;
    }

    public function setShortName(string $short_name): self
    {
        $this->short_name = $short_name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|Check[]
     */
    public function getChecks(): Collection
    {
        return $this->checks;
    }

    public function addCheck(Check $check): self
    {
        if (!$this->checks->contains($check)) {
            $this->checks[] = $check;
            $check->setBank($this);
        }

        return $this;
    }

    public function removeCheck(Check $check): self
    {
        if ($this->checks->removeElement($check)) {
            // set the owning side to null (unless already changed)
            if ($check->getBank() === $this) {
                $check->setBank(null);
            }
        }

        return $this;
    }
}

src/Entity/Check.php
<?php

namespace App\Entity;

use App\Repository\CheckRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CheckRepository::class)
 * @ORM\Table(name="`check`")
 */
class Check
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $payment_date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $number;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $amount;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=Bank::class, inversedBy="checks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $bank;

    public function __construct()
    {
        $this->payment_date = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPaymentDate(): ?\DateTimeInterface
    {
        return $this->payment_date;
    }

    public function setPaymentDate(\DateTimeInterface $payment_date): self
    {
        $this->payment_date = $payment_date;

        return $this;
    }

    public function getNumber(): ?string
    {
        return $this->number;
    }

    public function setNumber(string $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getAmount(): ?string
    {
        return $this->amount;
    }

    public function setAmount(string $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getBank(): ?Bank
    {
        return $this->bank;
    }

    public function setBank(?Bank $bank): self
    {
        $this->bank = $bank;

        return $this;
    }
}

src/Form/CheckType.php
<?php

namespace App\Form;

use App\Entity\Check;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CheckType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('payment_date', DateTimeType::class, [
                'label' => 'date of payment'
            ])
            ->add('number', NumberType::class, [
                'required' => true,
                'label' => 'account number'
            ])
            ->add('amount', NumberType::class, [
                'required' => true,
                'label' => 'cash amount (€)'
            ])
            ->add('description', TextareaType::class, [
                'label' => 'reason of the transfer'
            ])
            ->add('bank', null, [
                'label' => 'origin of the check',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Check::class,
        ]);
    }
}

src/Controller/CheckController.php
<?php

namespace App\Controller;

use App\Entity\Check;
use App\Form\CheckType;
use App\Repository\BankRepository;
use App\Repository\CheckRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

/**
 * @Route("/check")
 */
class CheckController extends AbstractController
{

    /**
     * @var CheckRepository
     */
    private $checkRepository;

    /**
     * @var EntityManagerInterface
     */
    private $em;

    /**
     * @var UrlGeneratorInterface
     */
    private $urlGenerator;

    /**
     * @var BankRepository
     */
    private $bankRepository;

    public function __construct(CheckRepository $checkRepository, EntityManagerInterface $em, UrlGeneratorInterface $urlGenerator, BankRepository $bankRepository)
    {
        $this->checkRepository = $checkRepository;
        $this->em = $em;
        $this->urlGenerator = $urlGenerator;
        $this->bankRepository = $bankRepository;
    }

    /**
     * @Route("/", name="check_list")
     */
    public function index(Request $request): Response
    {
        $offset = max(0, $request->query->getInt('offset', 0));
        $checksPaginator = $this->checkRepository->getCheckPaginator($offset);
        // $checks = $this->checkRepository->findAll();

        return $this->render('check/index.html.twig', [
            'checks' => $checksPaginator,
            'previous' => $offset - CheckRepository::PAGINATOR_PER_PAGE,
            'next' => min(count($checksPaginator), $offset + CheckRepository::PAGINATOR_PER_PAGE)
        ]);
    }

    /**
     * @Route("/{id}", name="check_show", requirements={"id"="\d+"})
     */
    public function show(Request $request, int $id)
    {
        $check = $this->checkRepository->findOneBy(['id' => $id]);
        return $this->render('check/single.html.twig', [
            'check' => $check
        ]);
    }

    /**
     * @Route("/edit/{id}", name="check_edit", requirements={"id"="\d+"}, methods={"GET", "POST"})
     */
    public function edit(Request $request, int $id)
    {
        $check = $this->checkRepository->findOneBy(['id' => $id]);

        $checkForm = $this->createForm(CheckType::class, $check);
        $checkForm->handleRequest($request);

        if ($checkForm->isSubmitted()&& $checkForm->isValid()) {
            $this->em->persist($check);
            $this->em->flush();

            return $this->redirect($this->urlGenerator->generate('check_show', ['id' => $id]), 302);
        }

        return $this->render('check/edit.html.twig', [
            'checkForm' => $checkForm->createView()
        ]);
    }

    /**
     * @Route("/new", name="check_new", methods={"GET", "POST"})
     */
    public function new(Request $request)
    {
        $check = new Check();
        $checkForm = $this->createForm(CheckType::class, $check);
        $checkForm->handleRequest($request);

        if ($checkForm->isSubmitted()&& $checkForm->isValid()) {
            $this->em->persist($check);
            $this->em->flush();

            return $this->redirect($this->urlGenerator->generate('check_list'), 302);
        }

        $banks = $this->bankRepository->findAll();

        return $this->render('check/new.html.twig', [
            'checkForm' => $checkForm->createView(),
        ]);
    }

    /**
     * @Route("/delete/{id}", name="check_delete", requirements={"id"="\d+"})
     */
    public function delete(Request $request, int $id)
    {
        $token_id = 'delete' . $id;

        if ($this->isCsrfTokenValid($token_id, $request->request->get('_token'))) {
            $check = $this->checkRepository->findOneBy(["id" => $id]);
            
            $this->em->remove($check);
            $this->em->flush();

            return $this->redirect($this->urlGenerator->generate('check_list'), 302);
        }

    }
}

templates/check/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modify Your Check{% endblock %}

{% block body %}
    <div class="check-edit">
        {{ form_start(checkForm) }}
        <div class="row">
            <div class="col-6">{{ form_row(checkForm.number) }}</div>
            <div class="col-6">{{ form_row(checkForm.amount) }}</div>
        </div>
        <div class="row">
            <div class="col-6">{{ form_row(checkForm.bank) }}</div>
            <div class="col-6">{{ form_row(checkForm.payment_date) }}</div>
        </div>
        <div class="row">
            <div class="col-12">{{ form_row(checkForm.description) }}</div>
        </div>
        <div class="row text-right">
            <div class="col-auto text-right">
                <button type="submit" class="btn btn-custom">Apply modifications</button>        
            </div>
        </div>
        {{ form_end(checkForm) }}
    </div>
{% endblock %}

templates/check/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Latest Checks{% endblock %}

{% block body %}
    <div class="check-list">
        <h2>Latest checks from all banks</h1>
        <div class="row mt-4">
            {% for check in checks %}

            <a class="col-4 check-item" href="{{ path('check_show', {id: check.id}) }}">
                <p class="amount">Amount: {{ check.amount|format_currency('EUR', locale="mg") }}</p>
                <p class="account">Account: {{ check.number }}</p>
                <p class="meta">By {{ check.bank.shortName }} on {{ check.paymentDate|date }}</p>
            </a>
            {% endfor %}
            {# controls #}
            <div class="controls">
            {% if previous >= 0 %}
            <p>
                <a href="{{ path('check_list', {offset: previous}) }}" class="control" id="previous">Previous</a></p>
            {% endif %}
            <p>
                <a href="{{ path('check_new') }}" class="control" id="new">Sign a new check</a></p>
            {% if next < checks|length %}
            <p>
                <a href="{{ path('check_list', {offset: next}) }}" class="control" id="next">Next</a></p>
            {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/check/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modify Your Check{% endblock %}

{% block body %}
    <div class="check-edit">
        {{ form_start(checkForm) }}
        <div class="row">
            <div class="col-6">{{ form_row(checkForm.number) }}</div>
            <div class="col-6">{{ form_row(checkForm.amount) }}</div>
        </div>
        <div class="row">
            <div class="col-6">{{ form_row(checkForm.bank) }}</div>
            <div class="col-6">{{ form_row(checkForm.payment_date) }}</div>
        </div>
        <div class="row">
            <div class="col-12">{{ form_row(checkForm.description) }}</div>
        </div>
        <div class="row text-right">
            <div class="col-auto text-right">
                <button type="submit" class="btn btn-custom">Create Now !!</button>        
            </div>
        </div>
        {{ form_end(checkForm) }}
    </div>
{% endblock %}

templates/check/single.html.twig
{% extends 'base.html.twig' %}

{% block title %}Latest Checks{% endblock %}

{% block body %}
    <div class="mt-4 check-single">
        <p>This check has been generated by {{ check.bank.name }} (<code>{{ check.bank.shortName }}</code>) on {{ check.paymentDate|format_datetime() }}. The receiving account number is <mark>{{ check.number }}</mark> with an amount of {{ check.amount|format_currency('EUR', locale="mg") }}. The reason of the transfer is as bellow:<br/>{{ check.description }}</p>
        <div class="controls">
            <a class="control" id="back" href="{{ path('check_list') }}">Back To List</a>
            <a class="control" id="edit" href="{{ path('check_edit', {id: check.id}) }}">Modify</a>
            <form method="POST" action="{{ path('check_delete', {id: check.id}) }}">
                {# <input type="hidden" name="_method" value="DELETE" /> #}
                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ check.id) }}" />
                <button id="delete" class="control">Tear the check</button>
            </form>
            {# <a class="control" id="delete" href="{{ path('check_delete', {id: check.id}) }}">Tear the check</a> #}
        </div>
    </div>
{% endblock %}